### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by tieorange** [mlykotom/valifi#28]
Please add a support for androidx.databinding.ViewBinding class.

Most modern apps are using androix

**Comment by mlykotom** [comment]
Is not Jetifier working for that? No problem, I will add the support, but it may take some time, so in the meantime - jetify it?

**Comment by mlykotom** [comment]
Updated library to version `1.4.0` with the androidx migration
https://github.com/mlykotom/valifi/releases/tag/1.4.0
